title: Alain Brown
description: software engineer building ai systems
url: "https://alainbrown.com"

author:
  name: Alain Brown
  url: "https://alainbrown.com"

twitter:
  card: summary_large_image

social:
  name: Alain Brown
  links:
    - https://github.com/alainbrown
    - https://linkedin.com/in/alainbrown

logo: https://github.com/alainbrown.png
image: /assets/og/default.png

markdown: kramdown
kramdown:
  input: GFM

permalink: /posts/:title/

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
