title: alain brown
description: machine learning engineer building ai systems
url: "https://ab10.org"

markdown: kramdown
kramdown:
  input: GFM

permalink: /posts/:title/

plugins:
  - jekyll-feed

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
